create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKpxpw7qa7k7scwns6b57iio3xg foreign key (user_user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (user_id bigint generated by default as identity, name varchar(255), primary key (user_id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint not null, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint not null, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint not null, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create table address (id bigint generated by default as identity, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint not null, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint not null, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
create sequence hibernate_sequence start with 1 increment by 1
create table address (id bigint not null, address1 varchar(255), user_id bigint, primary key (id))
create table user (id bigint not null, name varchar(255), primary key (id))
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user
